spring.application.name=integrahelp-backend
spring.datasource.url=jdbc:mysql://localhost:3306/integrahelp_db
spring.datasource.username=root
spring.datasource.password=0604
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=IntegraHelpSecretKey2024VeryLongSecretForHS256
jwt.expiration=86400000

server.port=8084
spring.servlet.multipart.max-file-size=10MB

logging.level.org.springframework.security=DEBUG